Repository Team-DogWalk/DogWalk, pull requests merged in 2024-11, with the labels that each got.

#23 UI: OAuth 로그인 화면 구현
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/Assets.xcassets/kakaotalk_sharing_btn_small.imageset/Contents.json
  DogWalk/Application/Assets.xcassets/kakaotalk_sharing_btn_small.imageset/kakaotalk_sharing_btn_small.png
  DogWalk/Presentatiton/Screens/Auth/AuthView.swift
Labels: 🏳️ Completed, 🎨 UI

#32 UI: Chatting 말풍선 구현 및 키보드 나타나기, 숨기기에 따른 예외처리 추가 구현
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/Assets.xcassets/TestAdCell.imageset/Contents.json
  DogWalk/Application/Assets.xcassets/TestAdCell.imageset/스크린샷 2024-10-28 오후 8.41.18 1.png
  DogWalk/Presentatiton/Components/Common/CommonSendView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoomView.swift
  DogWalk/Presentatiton/Screens/Chatting/MessageModel.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
Labels: 🏳️ Completed, 🎨 UI

#29 UI: HomeView 수정 + AuthView 문구 수정
  DogWalk/Application/Assets.xcassets/appleid_button (4).imageset/Contents.json
  DogWalk/Application/Assets.xcassets/appleid_button (4).imageset/appleid_button@2x (4).png
  DogWalk/Application/Assets.xcassets/kakao_login_medium_wide.imageset/Contents.json
  DogWalk/Application/Assets.xcassets/kakao_login_medium_wide.imageset/kakao_login_medium_wide.png
  DogWalk/Application/Assets.xcassets/kakaotalk_sharing_btn_small.imageset/kakaotalk_sharing_btn_small.png
  DogWalk/Presentatiton/Screens/Auth/AuthView.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
  DogWalk/Presentatiton/Utils/Extension/Font+.swift
Labels: 🏳️ Completed, 🎨 UI

#37 Feat: 채팅 사진 업로드 기능 구현
  DogWalk/Presentatiton/Components/Common/CommonSendView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoomView.swift
  DogWalk/Presentatiton/Screens/Chatting/MessageModel.swift
Labels: 🏳️ Completed, ✨ Feature, 🎨 UI

#40 Feat: Timer 구현완료
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Info.plist
  DogWalk/Presentatiton/Screens/Map/MapView.swift
  DogWalk/Presentatiton/Screens/Map/WarkResultView.swift
Labels: 🏳️ Completed, ✨ Feature

#38 Feat: 네트워크 통신 관련 데이터 모델 DTO 정의, API Router(Target) 구성 (1차)
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Data/DTOs/Remote/Auth/AuthDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/ChatRoomDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/ChatRoomResponseDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/LastChatDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/Request/GetChatListQuery.swift
  DogWalk/Data/DTOs/Remote/Chat/Request/NewChatRoomBody.swift
  DogWalk/Data/DTOs/Remote/Chat/Request/PostChatFileBody.swift
  DogWalk/Data/DTOs/Remote/Chat/Request/SendChatBody.swift
  DogWalk/Data/DTOs/Remote/DefaultRemoteDTO.swift
  DogWalk/Data/DTOs/Remote/Post/CommentDTO.swift
  DogWalk/Data/DTOs/Remote/Post/CreatorDTO.swift
  DogWalk/Data/DTOs/Remote/Post/GeolocationDTO.swift
  DogWalk/Data/DTOs/Remote/Post/LikePostDTO.swift
  DogWalk/Data/DTOs/Remote/Post/PostDTO.swift
  DogWalk/Data/DTOs/Remote/Post/PostResponseDTO.swift
  DogWalk/Data/DTOs/Remote/Post/Request/GetGeoLocationQuery.swift
  DogWalk/Data/DTOs/Remote/Post/Request/GetHashTagQuery.swift
  DogWalk/Data/DTOs/Remote/Post/Request/GetPostQuery.swift
  DogWalk/Data/DTOs/Remote/Post/Request/LikePostBody.swift
  DogWalk/Data/DTOs/Remote/Post/Request/PostBody.swift
  DogWalk/Data/DTOs/Remote/Post/Request/PostFileBody.swift
  DogWalk/Data/DTOs/Remote/Post/Request/PutPostBody.swift
  DogWalk/Data/DTOs/Remote/User/FollowDTO.swift
  DogWalk/Data/DTOs/Remote/User/KaKaoAppleLoginDTO.swift
  DogWalk/Data/DTOs/Remote/User/MyProfileDTO.swift
  DogWalk/Data/DTOs/Remote/User/Request/AppleLoginBody.swift
  DogWalk/Data/DTOs/Remote/User/Request/KaKaoLoginBody.swift
  DogWalk/Data/DTOs/Remote/User/UserProfileDTO.swift
  DogWalk/Data/DTOs/Remote/User/WithDrawDTO.swift
  DogWalk/Data/Network/APITarget.swift
  DogWalk/Data/Network/AuthTarget.swift
  DogWalk/Data/Network/ChatTarget.swift
  DogWalk/Data/Network/NetworkError.swift
  DogWalk/Data/Network/NetworkManager.swift
  DogWalk/Data/Network/PostTarget.swift
  DogWalk/Data/Network/TargetType.swift
  DogWalk/Data/Network/UserTarget.swift
  DogWalk/Presentatiton/Utils/Extension/String+.swift
Labels: 🏳️ Completed, ✨ Feature

#52 Refactor: WalkResultView MVI 구조화
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Presentatiton/Components/Base/Container.swift
  DogWalk/Presentatiton/Screens/Map/MapView.swift
  DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultIntent.swift
  DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultState.swift
  DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultView.swift
Labels: 🏳️ Completed, ✨ Feature

#58 Feat: LocationManager 클래스 추가 및 MapView에 위치 기능 연동
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Presentatiton/Screens/Map/LocationManager.swift
  DogWalk/Presentatiton/Screens/Map/MapView.swift
Labels: 🏳️ Completed, ✨ Feature

#57 Fix: 채팅방에서 채팅방 리스트로 나갈 때 탭바 사라지는 오류 해결
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoomView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingView.swift
  DogWalk/Presentatiton/Utils/Extension/View+.swift
Labels: 🐞 Bug, 🏳️ Completed

#59 Feat: Coordinator 구현
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/ContentView.swift
  DogWalk/Application/Coordinator/CoordinatorView.swift
  DogWalk/Application/Coordinator/DogWalkCoordinatorProtocol.swift
  DogWalk/Application/Coordinator/MainCoordinator.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingView.swift
  DogWalk/Presentatiton/Screens/Community/CommunityView.swift
Labels: 🏳️ Completed, ✨ Feature

#60 Feat: Access/RefreahToken 갱신 처리, 기존 네트워크 재호출 처리
  DogWalk/Data/DTOs/Remote/Auth/AuthDTO.swift
  DogWalk/Data/Network/AuthTarget.swift
  DogWalk/Data/Network/ChatTarget.swift
  DogWalk/Data/Network/NetworkError.swift
  DogWalk/Data/Network/NetworkManager.swift
  DogWalk/Data/Network/PostTarget.swift
  DogWalk/Data/Network/TargetType.swift
  DogWalk/Data/Network/UserTarget.swift
  DogWalk/Data/Repositories/Local/User/UserDefaults.swift
  DogWalk/Data/Repositories/Local/User/UserManager.swift
Labels: 🏳️ Completed, ✨ Feature

#61 Chore: WalkResultView conflict해결
  DogWalk.xcodeproj/project.pbxproj
Labels: 🏳️ Completed

#63 Fix: RetryHandler 실행 로직 수정
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Data/DTOs/Remote/User/OAuthLoginDTO.swift
  DogWalk/Data/Network/NetworkManager.swift
Labels: 🐞 Bug, 🏳️ Completed, ✨ Feature

#66 Feat: MapView에서 사용자가 이동한 path를 보여줌
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Info.plist
  DogWalk/Presentatiton/Screens/Map/LocationManager.swift
  DogWalk/Presentatiton/Screens/Map/MapView.swift
Labels: 🏳️ Completed, 🎨 UI

#68 Feat: 임시 로그인 기능 / 채팅방 목록 불러오기 구현
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/ContentView.swift
  DogWalk/Application/Coordinator/CoordinatorView.swift
  DogWalk/Application/Coordinator/DogWalkCoordinatorProtocol.swift
  DogWalk/Application/Coordinator/MainCoordinator.swift
  DogWalk/Application/DogWalkApp.swift
  DogWalk/Data/DTOs/Remote/Chat/ChatRoomDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/ChatRoomResponseDTO.swift
  DogWalk/Data/DTOs/Remote/User/OAuthLoginDTO.swift
  DogWalk/Data/DTOs/Remote/User/Request/EmailLoginBody.swift
  DogWalk/Data/Network/NetworkManager.swift
  DogWalk/Data/Network/UserTarget.swift
  DogWalk/Data/Repositories/Local/User/UserDefaults.swift
  DogWalk/Data/Repositories/Local/User/UserManager.swift
  DogWalk/Presentatiton/Components/Common/CommonTitleView.swift
  DogWalk/Presentatiton/Components/Modifier/ButtonWrapper.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListState.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift
  DogWalk/Presentatiton/Screens/Chatting/CreateChattingRoom/CreateChattingRoomIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/CreateChattingRoom/CreateChattingRoomState.swift
  DogWalk/Presentatiton/Screens/Chatting/CreateChattingRoom/CreateChattingRoomView.swift
  DogWalk/Presentatiton/Screens/CustomTab/CustomTabView.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
  DogWalk/Presentatiton/Screens/Login/LoginIntent.swift
  DogWalk/Presentatiton/Screens/Login/LoginState.swift
  DogWalk/Presentatiton/Screens/Login/LoginView.swift
  DogWalk/Presentatiton/Screens/Login/TestLoginAccount.swift
  DogWalk/Presentatiton/Screens/Map/CommunityView.swift
  DogWalk/Presentatiton/Utils/Extension/String+.swift
Labels: 🏳️ Completed, ✨ Feature

#69 Feat: 이미지 캐싱 구현
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Data/Repositories/Local/Image/ImageCacheManager.swift
  DogWalk/Presentatiton/Components/Common/CommonImageView.swift
  DogWalk/Presentatiton/Screens/Test/SMTestView.swift
Labels: 🏳️ Completed, ✨ Feature

#71 Feat: CoreData Repository 구현
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/DogWalkApp.swift
  DogWalk/Data/CoreData/Chat.xcdatamodeld/Chat.xcdatamodel/contents
  DogWalk/Data/CoreData/ChatMessage+CoreDataClass.swift
  DogWalk/Data/CoreData/ChatMessage+CoreDataProperties.swift
  DogWalk/Data/CoreData/ChatRoom+CoreDataClass.swift
  DogWalk/Data/CoreData/ChatRoom+CoreDataProperties.swift
  DogWalk/Data/CoreData/Repository/ChatRepository.swift
  DogWalk/Data/CoreData/Repository/CoreDataManager.swift
  DogWalk/Data/DTOs/Remote/User/MyProfileDTO.swift
  DogWalk/Data/Repositories/Local/CoreData/Chat.xcdatamodeld/Chat.xcdatamodel/contents
  DogWalk/Data/Repositories/Local/CoreData/ChatMessageRepository.swift
  DogWalk/Data/Repositories/Local/CoreData/ChatRoomRepository.swift
  DogWalk/Data/Repositories/Local/CoreData/DogProfile.xcdatamodeld/DogProfile.xcdatamodel/contents
  DogWalk/Data/Repositories/Local/User/UserDefaults.swift
  DogWalk/Data/Repositories/Local/User/UserManager.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingTestView.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
  DogWalk/Presentatiton/Screens/Map/CommunityView.swift
Labels: 🏳️ Completed, ✨ Feature

#74 Fix: Fixed CoreData path
  DogWalk.xcodeproj/project.pbxproj
Labels: 🐞 Bug, 🏳️ Completed

#76 Refactor: MapView-MVI
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/Coordinator/MainCoordinator.swift
  DogWalk/Presentatiton/Screens/CustomTab/CustomTabView.swift
  DogWalk/Presentatiton/Screens/Map/LocationManager.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapIntent.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapState.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
  DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultIntent.swift
  DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultState.swift
  DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultView.swift
Labels: 🏳️ Completed, 🔨 Refactoring

#86 Refactor: homeview-MVI 구현
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/Coordinator/MainCoordinator.swift
  DogWalk/Data/DTOs/Remote/Post/PostDTO.swift
  DogWalk/Data/Repositories/Local/DefaultLocalRepository.swift
  DogWalk/Presentatiton/Screens/CustomTab/CustomTabView.swift
  DogWalk/Presentatiton/Screens/Home/HomeIntent.swift
  DogWalk/Presentatiton/Screens/Home/HomeState.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
  DogWalk/Presentatiton/Screens/Login/LoginView.swift
  DogWalk/Presentatiton/Screens/Login/TestLoginAccount.swift
Labels: 🏳️ Completed, 🔨 Refactoring

#89 Refactor: 네트워크 Request 함수 DTO 반환 타입 추가
  DogWalk/Data/Network/NetworkManager.swift
Labels: 🏳️ Completed, ✨ Feature, 🔨 Refactoring

#90 Refactor: CommunityDetailView MVI 적용
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/Coordinator/MainCoordinator.swift
  DogWalk/Data/DTOs/Remote/Post/LikePostDTO.swift
  DogWalk/Data/DTOs/Remote/Post/PostDTO.swift
  DogWalk/Data/DTOs/Remote/Post/PostResponseDTO.swift
  DogWalk/Data/DTOs/Remote/Post/Request/CommentBody.swift
  DogWalk/Data/DTOs/Remote/Post/Request/GetGeoLocationQuery.swift
  DogWalk/Data/Network/NetworkManager.swift
  DogWalk/Data/Network/PostTarget.swift
  DogWalk/Data/Repositories/Local/Image/ImageCacheManager.swift
  DogWalk/Domain/UserCases/CommunityDetailUseCase.swift
  DogWalk/Domain/UserCases/CommunityUseCase.swift
  DogWalk/Presentatiton/Components/Base/ContentState.swift
  DogWalk/Presentatiton/Components/Common/CommonErrorView.swift
  DogWalk/Presentatiton/Components/Common/CommonLoadingView.swift
  DogWalk/Presentatiton/Components/Common/CommonProfile.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift
  DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailIntent.swift
  DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailState.swift
  DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift
  DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityState.swift
  DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityView.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
  DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultView.swift
  DogWalk/Presentatiton/Utils/Extension/Image+.swift
Labels: 🏳️ Completed, 🔨 Refactoring

#95 Refactor: HomeView UseCase 적용 및 weatherKit 구헌 및 CoreData CustomType 구…
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/Coordinator/MainCoordinator.swift
  DogWalk/Application/DogWalkApp.swift
  DogWalk/Data/CoreData/Chat.xcdatamodeld/Chat.xcdatamodel/contents
  DogWalk/Data/CoreData/ChatMessages.swift
  DogWalk/Data/CoreData/ChatMessagesTransformer.swift
  DogWalk/Data/CoreData/ChatRoom+CoreDataProperties.swift
  DogWalk/Data/CoreData/Repository/ChatRepository.swift
  DogWalk/Data/CoreData/Repository/CoreDataManager.swift
  DogWalk/Data/Repositories/Local/User/UserManager.swift
  DogWalk/DogWalk.entitlements
  DogWalk/Domain/UserCases/HomeUseCase.swift
  DogWalk/Presentatiton/Screens/Home/HomeContentState.swift
  DogWalk/Presentatiton/Screens/Home/HomeIntent.swift
  DogWalk/Presentatiton/Screens/Home/HomeState.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
  DogWalk/Presentatiton/Screens/Home/WeatherKitAPIManager.swift
  DogWalk/Presentatiton/Screens/Login/LoginView.swift
  DogWalk/Presentatiton/Screens/Login/TestLoginAccount.swift
  DogWalk/Presentatiton/Utils/Extension/CLLocation+.swift
Labels: 🏳️ Completed, ✨ Feature, 🔨 Refactoring

#101 Refactor: BackgroundMode에서 DispatchSourceTimer로 타이머 구현 변경
  DogWalk.xcodeproj/xcshareddata/xcschemes/DogWalk.xcscheme
  DogWalk/Info.plist
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapIntent.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapState.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
Labels: 🏳️ Completed, 🔨 Refactoring

#102 Feat: New 채팅방 만들기 구현
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Data/CoreData/Repository/ChatRepository.swift
  DogWalk/Data/Network/NetworkManager.swift
  DogWalk/Data/Repositories/Local/Image/ImageCacheManager.swift
  DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift
  DogWalk/Presentatiton/Screens/Home/HomeIntent.swift
Labels: 🏳️ Completed, ✨ Feature

#104 Feat: SocketIO 적용한 SocketIOManager 구현
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/DogWalkApp.swift
  DogWalk/Data/CoreData/Chat.xcdatamodeld/Chat.xcdatamodel/contents
  DogWalk/Data/CoreData/ChatRoom+CoreDataProperties.swift
  DogWalk/Data/CoreData/Repository/ChatRepository.swift
  DogWalk/Data/CoreData/Repository/CoreDataManager.swift
  DogWalk/Data/DTOs/Remote/Chat/ChattingDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/ChattingListDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/ChattingListResponseDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/ChattingResponseDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/ChattingRoomDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/ChattingRoomListResponseDTO.swift
  DogWalk/Data/DTOs/Remote/Chat/Request/PostChatFileBody.swift
  DogWalk/Data/DTOs/Remote/Chat/Request/SendChatBody.swift
  DogWalk/Data/DTOs/Remote/Chat/SocketDMDTO.swift
  DogWalk/Data/DTOs/Remote/Post/CommentDTO.swift
  DogWalk/Data/DTOs/Remote/Post/PostDTO.swift
  DogWalk/Data/Network/ChatTarget.swift
  DogWalk/Data/Network/NetworkManager.swift
  DogWalk/Data/Network/Socket/SocketError.swift
  DogWalk/Data/Network/Socket/SocketIOManager.swift
  DogWalk/Domain/UseCases/Chatting/ChattingListUseCase.swift
  DogWalk/Domain/UseCases/Chatting/ChattingRoomUseCase.swift
  DogWalk/Domain/UseCases/CommunityDetailUseCase.swift
  DogWalk/Domain/UseCases/CommunityUseCase.swift
  DogWalk/Domain/UseCases/DefaultSomeUseCase.swift
  DogWalk/Domain/UseCases/HomeUseCase.swift
  DogWalk/Presentatiton/Components/Base/ContentState.swift
  DogWalk/Presentatiton/Screens/Auth/AuthView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListState.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomState.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingTestView.swift
  DogWalk/Presentatiton/Screens/Chatting/CreateChattingRoom/CreateChattingRoomIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/CreateChattingRoom/CreateChattingRoomState.swift
  DogWalk/Presentatiton/Screens/Chatting/CreateChattingRoom/CreateChattingRoomView.swift
  DogWalk/Presentatiton/Screens/Chatting/MessageModel.swift
  DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityView.swift
  DogWalk/Presentatiton/Screens/Login/LoginView.swift
  DogWalk/Presentatiton/Utils/Extension/String+.swift
Labels: ✨ Feature, ⏳ In Progress

#113 Feat: CoreData Transformable Type 추가 및 Repository 메서드 추가
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Data/CoreData/CoreChatMessageTransformer.swift
  DogWalk/Data/CoreData/CoreChatRoom+CoreDataClass.swift
  DogWalk/Data/CoreData/CoreChatRoom+CoreDataProperties.swift
  DogWalk/Data/CoreData/CoreChatRoom.xcdatamodeld/CoreChatRoom.xcdatamodel/contents
  DogWalk/Data/CoreData/CustomType/CoreChatMessage.swift
  DogWalk/Data/CoreData/CustomType/CoreDataUserModel.swift
  DogWalk/Data/CoreData/CustomType/CoretLastChat.swift
  DogWalk/Data/CoreData/Repository/ChatRepository.swift
  DogWalk/Data/Network/Socket/SocketIOManager.swift
Labels: 🏳️ Completed

#121 Feat: MapView 로직 연결
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapIntent.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapState.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
Labels: 🏳️ Completed, ✨ Feature

#123 Feat: 채팅 전송 기능 구현 및 화면 연동
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Data/CoreData/Repository/ChatRepository.swift
  DogWalk/Data/Network/NetworkError.swift
  DogWalk/Data/Network/Socket/SocketIOManager.swift
  DogWalk/Domain/UseCases/Chatting/ChattingListUseCase.swift
  DogWalk/Domain/UseCases/Chatting/ChattingRoomUseCase.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomState.swift
Labels: 🏳️ Completed, ✨ Feature

#126 Fix:ResolveIssueWhereAnnotationClickDidNotLoadData
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/Assets.xcassets/AccentColor.colorset/Contents.json
  DogWalk/Application/Assets.xcassets/대체로 맑음.imageset/Contents.json
  DogWalk/Application/Assets.xcassets/대체로 맑음.imageset/대체로 맑음.jpeg
  DogWalk/Data/Network/NetworkManager.swift
  DogWalk/Domain/UseCases/MapUseCase.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapIntent.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapState.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
  DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultView.swift
  DogWalk/Presentatiton/Screens/Map/WalkResultCreate/WalkResultCreateView.swift
Labels: 🐞 Bug, 🏳️ Completed

#137 Fix: LoginView -> MainTab 이동시 뒤로가기 버튼 없애기
  DogWalk/Application/Coordinator/DogWalkCoordinatorProtocol.swift
  DogWalk/Application/Coordinator/MainCoordinator.swift
  DogWalk/Presentatiton/Screens/CustomTab/CustomTabView.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
Labels: 🏳️ Completed

#143 Fix: Modifiying MapView Logic
  DogWalk/Data/Network/NetworkManager.swift
  DogWalk/Data/Repositories/Local/User/UserManager.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapIntent.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapState.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
Labels: 🐞 Bug, 🏳️ Completed

#145 Feat: Socket Background Task
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/DogWalkApp.swift
  DogWalk/Data/CoreData/CustomType/CoreChatMessage.swift
  DogWalk/Data/Network/NetworkError.swift
  DogWalk/Data/Network/Socket/SocketIOManager.swift
  DogWalk/Data/Repositories/Local/User/UserDefaults.swift
  DogWalk/Data/Repositories/Local/User/UserManager.swift
  DogWalk/DogWalk/Data/CoreData/CoreChatRoom.xcdatamodeld/CoreChatRoom.xcdatamodel/contents
  DogWalk/Domain/UseCases/Chatting/ChattingRoomUseCase.swift
  DogWalk/Info.plist
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
  DogWalk/Presentatiton/Screens/Login/LoginView.swift
Labels: 🏳️ Completed, ✨ Feature

#149 Fix: 게시글 멍톡 연결
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/Coordinator/CoordinatorView.swift
  DogWalk/Data/CoreData/Repository/ChatRepository.swift
  DogWalk/Data/Network/Weather/WeatherKitAPIManager.swift
  DogWalk/Domain/UseCases/HomeUseCase.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift
  DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift
  DogWalk/Presentatiton/Screens/Home/HomeIntent.swift
  DogWalk/Presentatiton/Screens/Home/HomeState.swift
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
Labels: 🏳️ Completed

#151 Fix: 새로운 채팅 유저와 채팅시 오류 해결
  DogWalk/Data/CoreData/Repository/ChatRepository.swift
  DogWalk/Presentatiton/Components/Common/CommonSendView.swift
  DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift
Labels: 🏳️ Completed

#155 Feat:Merge LoginView Into Authview
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Application/Assets.xcassets/authImage.imageset/Contents.json
  DogWalk/Application/Assets.xcassets/authImage.imageset/authImage.jpeg
  DogWalk/Application/Coordinator/CoordinatorView.swift
  DogWalk/Presentatiton/Screens/Auth/AuthView.swift
  DogWalk/Presentatiton/Screens/Login/LoginView.swift
Labels: 🏳️ Completed, ✨ Feature

#156 Feat: 채팅 이미지 전송 기능 구현
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Data/CoreData/Repository/ChatRepository.swift
  DogWalk/Data/DTOs/Remote/Chat/LastChatDTO.swift
  DogWalk/Domain/UseCases/Chatting/ChattingRoomUseCase.swift
  DogWalk/Presentatiton/Components/Common/CommonImageView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift
Labels: 🏳️ Completed, ✨ Feature

#158 Refactor: 채팅룸 서치 구현 및 포스터 뷰 리팩토링 진행
  DogWalk/Data/Repositories/Local/Image/ImageCacheManager.swift
  DogWalk/Domain/UseCases/CommunityUseCase.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListState.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift
  DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift
  DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityIntent.swift
  DogWalk/Presentatiton/Screens/Community/MainCommunity/CommunityView.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
Labels: 🔨 Refactoring

#162 UI: 채팅방 입장 시 NavigationTitle 상대방 닉네임 처리, 이미지 셀 contentMode 수정
  DogWalk/Application/Coordinator/DogWalkCoordinatorProtocol.swift
  DogWalk/Application/Coordinator/MainCoordinator.swift
  DogWalk/Presentatiton/Components/Common/CommonImageView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingList/ChattingListView.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomIntent.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomState.swift
  DogWalk/Presentatiton/Screens/Chatting/ChattingRoom/ChattingRoomView.swift
  DogWalk/Presentatiton/Screens/Community/Detail/CommunityDetailView.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
Labels: 🏳️ Completed, 🎨 UI

#169 Chore: Modifying Images
  DogWalk.xcodeproj/project.pbxproj
  DogWalk/Presentatiton/Screens/Home/HomeView.swift
  DogWalk/Presentatiton/Screens/Map/WalkResult/WalkResultView.swift
Labels: 🏳️ Completed, 🎨 UI

#172 Refactor:exception and path handling in map view
  DogWalk/Presentatiton/Screens/Map/LocationManager.swift
  DogWalk/Presentatiton/Screens/Map/MapOverview/MapView.swift
Labels: 🏳️ Completed, 🔨 Refactoring
